### ISSUE TITLE
Multiple sheets and possibility to give a sheet name

### ISSUE THREAD

**Issue by mikel3361** [wqweto/Biff12Writer#1]
Is there a possibility to add more sheets and give a name for the sheet?
Sometimes i need more sheets inside the workbook.

Btw, as a workaround for the name i added it in the Init function and used this variable in Flush and it works,
but this cannot be done for multiple sheets...

Best regards, Mikel

**Comment by wqweto** [comment]
This will need new methods on `cBiff12Writer` and `cBiff12Container` probably.

I did not consider multi-sheet workbooks for the high-level `cBiff12Writer` class at all but it must be doable.

**Comment by mikel3361** [comment]
Added new function AddSheet in cBiff12Writer for myself and changed some parts of code to work perfecly as far i can see. Created file opens with no errors in excel application.  Init and Addsheet has optional parameter for a sheet name. I make a forge and a pull request if you interested.

Sample:
  
--- cut ---

  '--- setup xlsb writer
  Set oWriter = New cBiff12Writer
  oWriter.init 8, True, , "Page 1"   'optional sheetname at the end
  'With in chars (ColRowFactor defined as 260  seems to fit)
  oWriter.ColWidth(0) = oWriter.ColRowFactor * 18  
  oWriter.ColWidth(1) = oWriter.ColRowFactor * 14
  oWriter.ColWidth(2) = oWriter.ColRowFactor * 14
  oWriter.ColWidth(3) = oWriter.ColRowFactor * 6
  oWriter.ColWidth(4) = oWriter.ColRowFactor * 10
  oWriter.ColWidth(5) = oWriter.ColRowFactor * 90
  oWriter.ColWidth(6) = oWriter.ColRowFactor * 40
  oWriter.ColWidth(7) = oWriter.ColRowFactor * 20
    
  oWriter.AddRow
  oWriter.AddStringCell 0, "Entry 1:", oStyle2
  oWriter.AddNumberCell 4, 10, oStyle2
  oWriter.AddRow
  oWriter.AddStringCell 0, "Entry 2:", oStyle2
  oWriter.AddNumberCell 4, 20, oStyle2
  
  'Add new page afer last row
  oWriter.AddSheet "Page 2",  5    'add new sheet with name and ditterent col count (defaults to 1)
  oWriter.AddRow
  oWriter.AddStringCell 0, "Entry Page2:", oStyle2
  oWriter.AddNumberCell 4, 10, oStyle2

  'save the file  
  oWriter.SaveToFile NewFileName

--- end cut ---

Now the xlsb file has 2 sheets with name

hope this helps

**Comment by wqweto** [comment]
Hey, this is outstanding work!

This looks like the first PR of this caliber on any project of mine! You have to understand why I'm so excited here :-))

Anyway, I wrote some comments inline if you can take care of these in the PR before merging it or I can fix these later.

**Comment by wqweto** [comment]
Let me know when you think this is ready to be merged.

(I'm currently on vacation and a bit slow to answer this thread/PR)
